(***  Thing-O-Matic calibration script  ***)
(***                                    ***)
(*** This script will guide you through ***)
(*** calibrating the start position     ***)
(*** on your Thing-O-Matic.             ***)
M103 (disable RPM)
M73 P0 (enable build progress)
M18 (This disables the stepper motors.)
G162 Z F500 (Home Z axis maximum; go until reaching the end stop.)
G161 X Y F2500 (Home X and Y axis minimum; go until reaching the end stop.)
M73 P100 (End build progress)
M18 (disable stepper motors)
