(**** beginning of start.gcode ****)
(This file is for a MakerBot Cupcake CNC with)
(an automated build platform)
(**** begin initilization commands ****)
M103 (disable RPM)
M73 P0 (enable build progress)
G21 (set units to mm)
G90 (set positioning to absolute)
G92 X0 Y0 Z0 E0 (set origin to current position)
M104 S220 T0 (set extruder temperature)
M109 S120 T0 (set heated-build-platform temperature)
(**** end initilization commands ****)
(**** begin pre-wipe commands ****)
( Some people have had problems with the nozzle hitting )
( bolts or wipers during this pre-extrusion warmup.     )
( If this happens to you, you can change the values for )
( the X and Y positions in the following code.          )
( The goal is to have the toolhead wipe its initial     )
( extrusion near the edge of the platform, [anchor it]  )
( so as not to have it interfere with the print.        )
G1 X-54 Y-30 Z6 F3300.0 (move to waiting position)
M6 T0 (wait for tool to heat up)
G1 X-30 Y30 Z6 F3300.0 (move to initial position)
G1 Z0.6 F3300.0 (Go back down)
G92 E0 (Set E to 0)
G1 E4 F300 (Extrude 4mm of filament)
G92 E0 (Set E to 0 again)
(**** end pre-wipe commands ****)
(**** end of start.gcode ****)
