(******* End.gcode*******)
M109 S0 T0 ( Cool down the build platform )
M104 S0 T0 ( Cool down the Right Extruder )
M73 P100 ( End build progress )
G0 Z150 ( Send Z axis to bottom of machine )
M18 ( Disable steppers )
G162 X Y F2500 ( Home XY endstops )
M18 ( Disable stepper motors )
M70 P5 ( We <3 Making Things!)
M72 P1  ( Play Ta-Da song )
(*********end End.gcode*******)
